# ==========================================
# APPLICATION
# ==========================================

spring.application.name=CurrencyConveterWorld
spring.docker.compose.enabled=false

server.port=${PORT:8080}


# ==========================================
# MYSQL DATABASE
# ==========================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/currency_converter}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}


# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# GOOGLE OAUTH2
# ==========================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth

spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token

spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo

spring.security.oauth2.client.provider.google.user-name-attribute=sub


# ==========================================
# GMAIL SMTP
# ==========================================

==========================================
# BREVO TRANSACTIONAL EMAIL API
# ==========================================

brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=Currency Converter World
